notifications:
  email:
    - travis-ci@pimcore.org

sudo: false
language: php

php:
  - 7
  - 7.1

services:
  - redis

addons:
  mariadb: '10.1'
  hosts:
    - pimcore-test.dev

matrix:
  include:
    - os: linux
      sudo: required
      php: 7
      env:
          - PIMCORE_TEST_SUITE=rest PIMCORE_TEST_ENV=http
    - os: linux
      sudo: required
      php: 7.1
      env:
          - PIMCORE_TEST_SUITE=rest PIMCORE_TEST_ENV=http

cache:
  directories:
    - vendor

env:
  global:
    - COMPOSER_FLAGS="--no-interaction --optimize-autoloader"
    - PIMCORE_ENVIRONMENT=test
    - PIMCORE_TEST=1
    - PIMCORE_TEST_URL=http://pimcore-test.dev
    - PIMCORE_TEST_DB_DSN="mysql://root@localhost/pimcore_test"
    - PIMCORE_TEST_CACHE_REDIS_DATABASE=1

before_install:
  - mysql --version
  - mysql -e "CREATE DATABASE pimcore_test;"
  - composer global show -ND 2>&1 | grep "hirak/prestissimo" || travis_retry composer global require $COMPOSER_FLAGS hirak/prestissimo

install:
  # add config templates
  - mkdir -p var/config
  - cp .travis/system.template.php var/config/system.php
  - cp app/config/parameters.example.yml app/config/parameters.yml
  - echo $COMPOSER_FLAGS

  # install composer - HHVM isn't officially PHP 7 compatible - see https://github.com/composer/composer/issues/4976
  - if [[ "$TRAVIS_PHP_VERSION" != *"hhvm"* ]]; then composer install $COMPOSER_FLAGS; fi
  - if [[ "$TRAVIS_PHP_VERSION" == *"hhvm"* ]]; then composer install $COMPOSER_FLAGS --ignore-platform-reqs; fi

before_script:
  - .travis/setup-php.sh
  - if [[ "$TRAVIS_SUDO" == "true" ]]; then .travis/setup-sudo.sh; fi

script:
  - .travis/run-tests.sh
